---
- name: Prepare database names for SQL script
  set_fact:
    db_names_sql: "{{ db_names | map('quote') | join(', ') }}"

- name: Create backup folder
  win_file:
    path: '{{ bak_path }}'
    state: directory
  #when: "{{ inventory_hostname == 'jnreward_db' }}"
  #delegate_to: jnreward_db
  notify: BackUpFolder Created
  ignore_errors: true
  register: result
- name: Generate SQL script from template
  template:
    src: ../templates/backup.sql.j2
    dest: "{{bak_path}} + 'backup.sql'"

- name: Execute SQL script on database
  win_shell: |
    Invoke-Sqlcmd -ServerInstance "localhost"  -InputFile "{{bak_path}} + 'backup.sql'" 
  register: sql_output

